version: '3.8'
services:
  backend:
    build:
      context: .  # Set context to the project root directory
      dockerfile: Backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=video-streaming-service
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=eu-central-1
      - AWS_STACK_AUTO=false
      - SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE=100MB
      - SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE=100MB
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27018:27017"
  frontend:
    build: .
    ports:
      - "4200:80"
